# Generated by Django 3.2 on 2023-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_testmodel_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='nullable',
            field=models.TextField(blank=True, null=True, verbose_name='Какой-то текст'),
        ),
    ]
